### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by JIzabal** [yash-lol/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
  - Picture is missing the output of `testsnip1other`
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:
You have extra items in your list for the expected output of `testsnip3` and `testsnip3other`. You should only be collecting markdown links and not normal links. [The CommonMark demo site](https://spec.commonmark.org/dingus/) can help to see what output you should have, because it should only highlight markdown links.

Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by yash-lol** [comment]
Hey!
I'm so sorry, but I had actually forgotten to commit my changes on the
lab-report4-week-8 page, But I just did it.
It would be great if you could take a look at it, but I totally understand
if I have to do the resubmissions.
Thank you!
Yash Joshi

**Comment by JIzabal** [comment]
No worries, thanks for committing the changes! I've regraded what you have now, and once you fix the issues I pointed out, I'll fix your grade.

**Comment by yash-lol** [comment]
Hey!
I'm sorry for the delay in the corrections, but my laptop has not been running vscode well lately, so I had to use a different laptop to make these corrections.
Thank you for your time!

**Comment by yash-lol** [comment]
Hey!
I've made the required changes for lab report 4, and I had left a note on
Github. I was wondering if you have had the time to look at it.
Thank you so much for your time!

**Comment by JIzabal** [comment]
Great job!

**Comment by yash-lol** [comment]
Thank you so much! <3

**Comment by JIzabal** [comment]
No problem!
